services:
  - name: streamlit-app
    type: web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m streamlit run Home.py --server.port $PORT --server.enableCORS false
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    buildFilter:
      paths:
        - ai traffic/**
    plan: free
    rootDir: ai traffic

  - name: django-backend
    type: web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py runserver 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    buildFilter:
      paths:
        - aipowered_cyber_threat_intelligence/**
    plan: free
    rootDir: aipowered_cyber_threat_intelligence
