services:
  - type: web
    name: django-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn aipowered_cyber_threat_intelligence.wsgi
    envVars:
      - key: DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        value: 'django-insecure-myt#yi36g8q)2draq7*kugc)x#ioa2og%k68bc1($=k@)v2jld'

    - type: web
    name: streamlit-frontend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port 10000 --server.address 0.0.0.0
