services:
    startCommand: python aipowered_cyber_threat_intelligence/manage.py runserver 0.0.0.0:$PORT
  - name: streamlit-app
    type: web
    env: python
    rootDir: ai traffic
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run Home.py --server.port $PORT --server.enableCORS false
    plan: free

  - name: django-backend
    type: web
    env: python
    rootDir: aipowered_cyber_threat_intelligence
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py runserver 0.0.0.0:$PORT
    plan: free
